insert into artists (artist_name) values ('Metallica');
insert into artists (artist_name) values ('Slipknot');
insert into artists (artist_name) values ('Korn');
insert into artists (artist_name) values ('Slayer');
insert into artists (artist_name) values ('Nuclear test');
insert into artists (artist_name) values ('Crusher');
insert into artists (artist_name) values ('Lich king');
insert into artists (artist_name) values ('Hexen');
insert into artists (artist_name) values ('Good Charlotte');
insert into artists (artist_name) values ('Sunstorm');
insert into artists (artist_name) values ('King 810');
insert into artists (artist_name) values ('Mad Hatter');

insert into albums (album_name, album_year) values ('S&M2', '2020');
insert into albums (album_name, album_year) values ('Pieces of Reality', '2020');
insert into albums (album_name, album_year) values ('Mad Hatter', '2018');
insert into albums (album_name, album_year) values ('Generation Rx', '2018');
insert into albums (album_name, album_year) values ('The Repentless Killogy', '2019');
insert into albums (album_name, album_year) values ('We Are Not Your Kind', '2019');
insert into albums (album_name, album_year) values ('The nothing', '2019');
insert into albums (album_name, album_year) values ('Suicide King', '2019');

insert into participants (artist_id, album_id) values (1, 1);
insert into participants (artist_id, album_id) values (12, 2);
insert into participants (artist_id, album_id) values (12, 3);
insert into participants (artist_id, album_id) values (9, 4);
insert into participants (artist_id, album_id) values (4, 5);
insert into participants (artist_id, album_id) values (2, 6);
insert into participants (artist_id, album_id) values (3, 7);
insert into participants (artist_id, album_id) values (11, 8);

insert into tracks (track_name, track_length, album_id) values ('For Whom the Bell Tolls', '4:37', 1);
insert into tracks (track_name, track_length, album_id) values ('The Day That Never Comes', '8:27', 1);
insert into tracks (track_name, track_length, album_id) values ('The Memory Remains', '5:42', 1);
insert into tracks (track_name, track_length, album_id) values ('Confusion', '6:41', 1);
insert into tracks (track_name, track_length, album_id) values ('Moth into Flame', '6:18', 1);
insert into tracks (track_name, track_length, album_id) values ('Generation Rx', '2:07', 4);
insert into tracks (track_name, track_length, album_id) values ('Self Help', '3:24', 4);
insert into tracks (track_name, track_length, album_id) values ('Shadowboxer', '3:05', 4);
insert into tracks (track_name, track_length, album_id) values ('Actual Pain', '3:44', 4);
insert into tracks (track_name, track_length, album_id) values ('Prayers', '3:50', 4);
insert into tracks (track_name, track_length, album_id) values ('The Darkness is Revealing', '3:40', 7);
insert into tracks (track_name, track_length, album_id) values ('Idiosyncrasy', '4:39', 7);
insert into tracks (track_name, track_length, album_id) values ('Gravity Of Discomfort', '3:35', 7);
insert into tracks (track_name, track_length, album_id) values ('This Loss', '4:41', 7);

insert into genre_artist (genre_id, artist_id) values (1, 1);
insert into genre_artist (genre_id, artist_id) values (1, 4);
insert into genre_artist (genre_id, artist_id) values (1, 5);
insert into genre_artist (genre_id, artist_id) values (1, 6);
insert into genre_artist (genre_id, artist_id) values (1, 7);
insert into genre_artist (genre_id, artist_id) values (1, 8);
insert into genre_artist (genre_id, artist_id) values (2, 9);
insert into genre_artist (genre_id, artist_id) values (3, 10);
insert into genre_artist (genre_id, artist_id) values (4, 2);
insert into genre_artist (genre_id, artist_id) values (4, 3);
insert into genre_artist (genre_id, artist_id) values (4, 11);
insert into genre_artist (genre_id, artist_id) values (5, 12);
insert into genre_artist (genre_id, artist_id) values (1, 12);

insert into compilations (compilation_name, compilation_year) values ('Some NU metall', 2021);
insert into compilations (compilation_name, compilation_year) values ('Some Trash metall', 2021);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.1', 2021);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.2', 2019);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.3', 2021);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.4', 2021);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.5', 2021);
insert into compilations (compilation_name, compilation_year) values ('Voice vol.6', 2021);

insert into tracklist (track_id, compilation_id) values (12, 1);
insert into tracklist (track_id, compilation_id) values (13, 1);
insert into tracklist (track_id, compilation_id) values (14, 1);
insert into tracklist (track_id, compilation_id) values (1, 2);
insert into tracklist (track_id, compilation_id) values (2, 2);
insert into tracklist (track_id, compilation_id) values (3, 2);
insert into tracklist (track_id, compilation_id) values (4, 2);
insert into tracklist (track_id, compilation_id) values (15, 3);
insert into tracklist (track_id, compilation_id) values (14, 3);
insert into tracklist (track_id, compilation_id) values (13, 3);
insert into tracklist (track_id, compilation_id) values (12, 3);
insert into tracklist (track_id, compilation_id) values (3, 4);
insert into tracklist (track_id, compilation_id) values (5, 4);
insert into tracklist (track_id, compilation_id) values (7, 4);
insert into tracklist (track_id, compilation_id) values (9, 4);
insert into tracklist (track_id, compilation_id) values (2, 5);
insert into tracklist (track_id, compilation_id) values (4, 5);
insert into tracklist (track_id, compilation_id) values (6, 5);
insert into tracklist (track_id, compilation_id) values (8, 5);
insert into tracklist (track_id, compilation_id) values (8, 6);
insert into tracklist (track_id, compilation_id) values (9, 6);
insert into tracklist (track_id, compilation_id) values (10, 6);
insert into tracklist (track_id, compilation_id) values (11, 6);
insert into tracklist (track_id, compilation_id) values (1, 7);
insert into tracklist (track_id, compilation_id) values (10, 7);
insert into tracklist (track_id, compilation_id) values (13, 7);
insert into tracklist (track_id, compilation_id) values (11, 7);
insert into tracklist (track_id, compilation_id) values (7, 8);
insert into tracklist (track_id, compilation_id) values (14, 8);
insert into tracklist (track_id, compilation_id) values (6, 8);
insert into tracklist (track_id, compilation_id) values (12, 8);
